defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: ""
  aws_secret_access_key: ""
  fog_directory: "tyne-assets"
  gzip_compression: true
  existing_remote_files: delete

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
